### PR TITLE
readme

### PR DESCRIPTION
**Pull request by yaruwangway**
add README

### CODE REVIEW

**Comment by yaruwangway** [comment]
- README describes how presently pooltoy works.
- README will be changed later when the `user-create` part in the code is changed, and when new functions are added.

**Comment by okwme** [comment]
is this ready for review (R4R)? If not it would be good to mark it as a draft either with the "Convert to draft" button above or by putting "DRAFT:" at the beginning of the title.

**Comment by yaruwangway** [comment]
> is this ready for review (R4R)? If not it would be good to mark it as a draft either with the "Convert to draft" button above or by putting "DRAFT:" at the beginning of the title.

Yes, it is ready for review.

**Comment by okwme** [comment]
I'm gonna merge already since it already does a great job of explaining things and we can add more to it later

**Pull request merged**
